//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepartmentTreeData
{
    using System;
    using System.Collections.Generic;
    
    public partial class departments
    {
        public int id { get; set; }
        public string name { get; set; }
        public int parent_id { get; set; }
    }
}
